server:
  port: 9000
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://172.16.1.45:3306/auth-practice?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver